### ISSUE TITLE
Is this library thread-safe?

### ISSUE THREAD

**Issue by rockingdice** [crust/beehive#3]
I'm working on a server app that simulates game battles, each battle will simulate in an isolated thread, I found you used the static method to generate ids, if I change that, can I use it in different threads?

**Comment by cbush** [comment]
Hi, thanks for your question. I think this library was not written with thread-safety in mind, but we could probably make it use an atomic integer for that counter.

**Comment by cbush** [comment]
That said, everything else should be inherently thread-local. I don't think there is shared state at all except what you pass in. So as long as you are keeping your state objects thread-local or otherwise threadsafe, you should be able to use copies of the behavior trees in multiple threads.

**Comment by rockingdice** [comment]
@cbush Thanks, that's exactly what I'm looking for.
